language: python
python:
  - "3.4"
  - "3.6"
  - "3.7"
  #- "3.8"
before_install:
- sudo apt-get -qq update
# Make sure python development tools are installed
- sudo apt-get install -y python3-dev python3-setuptools
# Install GMP
- sudo apt-get install -y libgmp10 libgmp-dev
# Install PBC
#- wget http://voltar.org/pbcfiles/libpbc0_0.5.12_amd64.deb
#- wget http://voltar.org/pbcfiles/libpbc-dev_0.5.12_amd64.deb
#- sudo dpkg -i libpbc0_0.5.12_amd64.deb
#- sudo dpkg -i libpbc-dev_0.5.12_amd64.deb
# Install OpenSSL
- sudo apt-get install -y openssl
install:
- pip install -r requirements.txt
- ./configure.sh
- cd ./deps/pbc && make && sudo ldconfig && cd -
- make
- make install && sudo ldconfig
script:
- make test
